### ISSUE TITLE
Host::peers not working as intended + question about storing peers

### ISSUE THREAD

**Issue by Bravo555** [futile/enet-rs#3]
Hello there!

I've started using using this library because I was working on a game with some friends, the project was discontinued, but I still fiddle with the library, trying to get something working, and I like it so far!

That said, as I haven't used this library before, I ran into some issues.

I have `Client` and `Server` structs:
```rust
struct Client {
    host: enet::Host,
    server: enet::Peer<()>,
}

struct Server {
   host: enet::Host,
   clients: Vec<enet::Peer<()>,
}
```

As you can see, I want to store the peers so that I can send stuff to them. Now, I'm aware that the documentation says:
>[The lifetime of these instances is not really clear from the ENet documentation. Therefore, Peers are always borrowed, and can not really be stored anywhere.](https://docs.rs/enet/0.2.0/enet/struct.Peer.html)

And indeed I've tried to add lifetimes to my structs, but to no avail.

Then, I noticed method `Host::peers()` and thought that I don't really have to store the peers if `Host` stores connected peers for me. But whether I connect my client to the server or not, `peers()` always returns an iterator over 10 peers (so maximum numbers of peers i provided in a constuctor, as I'm using code from the examples, just with these structs above).

So, what's the correct method to use the library in bigger projects that involve structs? Because I reckon you have to store the peers somehow.

**Comment by futile** [comment]
Hi,

yes, unfortunately `Host::peers()` always returns all peers that you have allocated space for when you created the `Host`. (That is, exactly the `max_peer_count` argument you gave to `Enet::create_host()`, which you already noticed.)

The trick is to check which of these `Peers` are connected. See for example [this snippet](https://github.com/futile/crufty/blob/master/src/net/server.rs#L182-L185):

```rust
for mut peer in self.enet_host.peers() {
  if peer.state() != PeerState::Connected {
    continue;
  }
```

This is due to how the enet library itself works, see `peerCount` and `peers` [here](http://enet.bespin.org/structENetHost.html#a7cb88cfe75cb49f48515a75d2f0fb229).

After working with enet for a while, I came to the conclusion that its API is not really that nice to use; as demonstrated by this issue and the unclear lifetime semantics of Peers in general. That said, I didn't find that many other libraries that provide similar features, so dealing with a few quirks here and there might be completely worthwhile. One other project I'm aware of is amethyst's [laminar](https://github.com/amethyst/laminar). However, I'm not sure exactly what state that project is in currently.

I hope that helps! Is this explanation useful to you?

**Comment by Bravo555** [comment]
Yes, thank you for the swift reply! One thing I would suggest is to change the description of the method in the documentation. Right now it says 

>[Returns an iterator over all peers connected to this Host](https://docs.rs/enet/0.2.0/enet/struct.Host.html#method.peers)

which is a bit misleading, because not all peers are connected.

Your explanation was indeed helpful. Thanks!
